version: "3.7"
services:
  app:
    build:
      args:
        user: yulia
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: quis2
    container_name: quis2-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - quis2

  db:
    image: mysql:8.0
    container_name: quis2-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: quis2
      MYSQL_ROOT_PASSWORD: yulia
      MYSQL_PASSWORD: yulia
      MYSQL_USER: yulia
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - quis2

  nginx:
    image: nginx:alpine
    container_name: quis2-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - quis2

networks:
  kuis2:
    driver: bridge
